# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # For Helm Operations
  helmChartPath: '$(Build.SourcesDirectory)/webfrontendchart'
  helmChartTemplatePath: '$(Build.SourcesDirectory)/webfrontendchart/templates'
  configFile: '$(Build.SourcesDirectory)/webfrontendchart/templates/deployment.yaml'
  
  # For Github Operations
  githubOrganization: 'ameliawang0914'
  githubRepository: 'webfrontend'
  targetBranch: 'fix/kubescore-misconfig'
  commitMessage: 'Fix misconfigurations detected by KubeScore'
  pullRequestTitle: 'Fix KubeScore misconfigurations'
  pullRequestDescription: 'This PR fixes misconfigurations detected by KubeScore.'
  sourceBranch: 'main'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '939bd1b2-1339-48d9-9412-daedab7d2060'
  imageRepository: 'amywebfrontend'
  containerRegistry: 'amyacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Scanning Helm charts..."
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        wget -O /usr/local/bin/kube-score https://github.com/zegl/kube-score/releases/download/v1.11.0/kube-score_1.11.0_linux_amd64
        chmod +x /usr/local/bin/kube-score
        helm lint $(helmChartPath)
        helm template $(helmChartPath) | kube-score score - > kube-score-report.txt
        echo "kube-score-report completed"
        cat kube-score-report.txt
        echo "cat kube-score-report completed"
      displayName: 'Lint and scan Helm charts'
      continueOnError: false
    
    - script: |
        python fix_misconfig_kubescore.py kube-score-report.txt $(configFile)
      displayName: 'Fix KubeScore misconfigurations'
      continueOnError: false
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get update
          sudo apt-get install -y gh
      displayName: 'Install GitHub CLI'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          git status
          git config --global user.email "yuewangapply@gmail.com"
          git config --global user.name "Wang Yue"

          git checkout -b $(targetBranch)
      
          # Assuming fix_kubescore.py made changes to the config file
          git add $(configFile)
          git commit -m "$(commitMessage)"
          git push origin $(targetBranch)
      
          # Create Pull Request using GitHub CLI
          git auth status
          # gh auth login --with-token
          # gh pr create --title "$(pullRequestTitle)" --body "$(pullRequestDescription)" --base $(sourceBranch) --head $(targetBranch)
      displayName: 'Create Pull Request on GitHub'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
